"""create monitors table

Revision ID: 678ab92a0abc
Revises: 8b9118d2bd7b
Create Date: 2026-08-08 16:16:11.901156

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "678ab92a0abc"
down_revision: str | Sequence[str] | None = "8b9118d2bd7b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "monitors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "GET",
                name="monitor_http_method",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="GET",
            nullable=False,
        ),
        sa.Column("interval_seconds", sa.Integer(), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "expected_status", sa.Integer(), server_default="200", nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "UP",
                "DOWN",
                "DEGRADED",
                "PAUSED",
                "UNKNOWN",
                name="monitor_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="UNKNOWN",
            nullable=False,
        ),
        sa.Column(
            "failure_threshold", sa.Integer(), server_default="3", nullable=False
        ),
        sa.Column(
            "recovery_threshold", sa.Integer(), server_default="2", nullable=False
        ),
        sa.Column(
            "consecutive_failures", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "consecutive_successes", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_check_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "consecutive_failures >= 0", name="consecutive_failures_nonnegative"
        ),
        sa.CheckConstraint(
            "consecutive_successes >= 0", name="consecutive_successes_nonnegative"
        ),
        sa.CheckConstraint(
            "expected_status BETWEEN 100 AND 599", name="expected_status_range"
        ),
        sa.CheckConstraint(
            "failure_threshold BETWEEN 1 AND 10", name="failure_threshold_range"
        ),
        sa.CheckConstraint(
            "interval_seconds BETWEEN 30 AND 86400", name="interval_seconds_range"
        ),
        sa.CheckConstraint(
            "recovery_threshold BETWEEN 1 AND 10", name="recovery_threshold_range"
        ),
        sa.CheckConstraint(
            "timeout_seconds BETWEEN 1 AND 60", name="timeout_seconds_range"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_monitors_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_monitors")),
    )
    op.create_index(
        "ix_monitors_is_active_next_check_at",
        "monitors",
        ["is_active", "next_check_at"],
        unique=False,
    )
    op.create_index(op.f("ix_monitors_user_id"), "monitors", ["user_id"], unique=False)
    op.create_index(
        "ix_monitors_user_id_status", "monitors", ["user_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_monitors_user_id_status", table_name="monitors")
    op.drop_index(op.f("ix_monitors_user_id"), table_name="monitors")
    op.drop_index("ix_monitors_is_active_next_check_at", table_name="monitors")
    op.drop_table("monitors")
    # ### end Alembic commands ###
