"""create incidents table

Revision ID: 8918ff3f3598
Revises: d26846576b6f
Create Date: 2026-08-08 21:54:07.433511

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8918ff3f3598"
down_revision: str | Sequence[str] | None = "d26846576b6f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incidents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("monitor_id", sa.Uuid(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "RESOLVED",
                name="incident_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="OPEN",
            nullable=False,
        ),
        sa.Column("failure_reason", sa.String(length=500), nullable=False),
        sa.Column("initial_check_id", sa.BigInteger(), nullable=False),
        sa.Column("recovery_check_id", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "\n            (\n                status = 'OPEN'\n                AND resolved_at IS NULL\n                AND recovery_check_id IS NULL\n            )\n            OR\n            (\n                status = 'RESOLVED'\n                AND resolved_at IS NOT NULL\n                AND recovery_check_id IS NOT NULL\n            )\n            ",
            name="incident_resolution_consistency",
        ),
        sa.ForeignKeyConstraint(
            ["initial_check_id"],
            ["monitor_checks.id"],
            name=op.f("fk_incidents_initial_check_id_monitor_checks"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["monitor_id"],
            ["monitors.id"],
            name=op.f("fk_incidents_monitor_id_monitors"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recovery_check_id"],
            ["monitor_checks.id"],
            name=op.f("fk_incidents_recovery_check_id_monitor_checks"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incidents")),
    )
    op.create_index(
        "ix_incidents_monitor_id_started_at",
        "incidents",
        ["monitor_id", "started_at"],
        unique=False,
    )
    op.create_index(
        "uq_incidents_open_monitor_id",
        "incidents",
        ["monitor_id"],
        unique=True,
        postgresql_where=sa.text("status = 'OPEN'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_incidents_open_monitor_id",
        table_name="incidents",
        postgresql_where=sa.text("status = 'OPEN'"),
    )
    op.drop_index("ix_incidents_monitor_id_started_at", table_name="incidents")
    op.drop_table("incidents")
    # ### end Alembic commands ###
