"""optimize monitor check pagination

Revision ID: aefed0db8743
Revises: 2259f3ffcd63
Create Date: 2026-08-12 10:24:20.826056

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aefed0db8743"
down_revision: str | Sequence[str] | None = "2259f3ffcd63"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_monitor_checks_monitor_id_checked_at"), table_name="monitor_checks"
    )
    op.create_index(
        "ix_monitor_checks_monitor_id_checked_at_id",
        "monitor_checks",
        [
            "monitor_id",
            sa.literal_column("checked_at DESC"),
            sa.literal_column("id DESC"),
        ],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_monitor_checks_monitor_id_checked_at_id", table_name="monitor_checks"
    )
    op.create_index(
        op.f("ix_monitor_checks_monitor_id_checked_at"),
        "monitor_checks",
        ["monitor_id", sa.literal_column("checked_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###
