"""create hourly monitor metrics

Revision ID: ff2abd28db1e
Revises: aefed0db8743
Create Date: 2026-08-12 11:39:28.870921

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff2abd28db1e"
down_revision: str | Sequence[str] | None = "aefed0db8743"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "monitor_hourly_metrics",
        sa.Column("monitor_id", sa.Uuid(), nullable=False),
        sa.Column("hour", sa.DateTime(timezone=True), nullable=False),
        sa.Column("total_checks", sa.Integer(), nullable=False),
        sa.Column("successful_checks", sa.Integer(), nullable=False),
        sa.Column("failed_checks", sa.Integer(), nullable=False),
        sa.Column("average_response_time_ms", sa.Float(), nullable=False),
        sa.Column("min_response_time_ms", sa.Integer(), nullable=False),
        sa.Column("max_response_time_ms", sa.Integer(), nullable=False),
        sa.Column("uptime_percentage", sa.Float(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "\n            average_response_time_ms >= 0\n            AND min_response_time_ms >= 0\n            AND max_response_time_ms >= 0\n            AND min_response_time_ms <= max_response_time_ms\n            ",
            name="hourly_metrics_response_times_valid",
        ),
        sa.CheckConstraint(
            "\n            successful_checks >= 0\n            AND failed_checks >= 0\n            ",
            name="hourly_metrics_check_counts_nonnegative",
        ),
        sa.CheckConstraint(
            "\n            total_checks =\n                successful_checks + failed_checks\n            ",
            name="hourly_metrics_check_counts_consistent",
        ),
        sa.CheckConstraint(
            "total_checks > 0", name="hourly_metrics_total_checks_positive"
        ),
        sa.CheckConstraint(
            "uptime_percentage BETWEEN 0 AND 100",
            name="hourly_metrics_uptime_percentage_range",
        ),
        sa.ForeignKeyConstraint(
            ["monitor_id"],
            ["monitors.id"],
            name=op.f("fk_monitor_hourly_metrics_monitor_id_monitors"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "monitor_id", "hour", name=op.f("pk_monitor_hourly_metrics")
        ),
    )
    op.create_index(
        "ix_monitor_hourly_metrics_hour",
        "monitor_hourly_metrics",
        ["hour"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_monitor_hourly_metrics_hour", table_name="monitor_hourly_metrics")
    op.drop_table("monitor_hourly_metrics")
    # ### end Alembic commands ###
